Corrections to Terraform manifest
yandex-cloud-examples/yc-data-proc-metadata-import pull request #6
Opened 2024-12-10 10:13 UTC by mikhaildoc-documentat

2024-12-28 06:35 UTC, Odyvia42 requested changes

2024-12-28 06:35 UTC, Odyvia42 commented on metastore-import.tf
> +  os_sa_name           = "sa-for-obj-storage" # Name of the service account for Object Storage creating
```suggestion
  os_sa_name           = "sa-for-obj-storage" # Name of the service account for managing Object Storage bucket and bucket's ACLs
```

2024-12-28 06:35 UTC, Odyvia42 commented on metastore-import.tf
> -
А вот тут поясни, пожалуйста: в других манифестах ты это правило добавляешь, а отсюда убираешь. Так надо?

2024-12-28 06:35 UTC, Odyvia42 commented on metastore-import.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Здесь было правильно. Давай вернём как было.

2024-12-28 06:35 UTC, Odyvia42 commented on metastore-import.tf
Давай добавим в кластер зависимости от ресурсов с ролями `dataproc.agent` и `dataproc.provisioner`, как в других манифестах.

2024-12-28 06:35 UTC, Odyvia42 commented on metastore-import.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Здесь было правильно. Давай вернём как было.

2025-01-09 10:20 UTC, mikhaildoc-documentat commented on metastore-import.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так, как я исправил. См. пример в https://developer.hashicorp.com/terraform/language/functions/file

2025-01-09 10:21 UTC, mikhaildoc-documentat commented on metastore-import.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так, как я исправил. См. пример в https://developer.hashicorp.com/terraform/language/functions/file

2025-01-09 10:22 UTC, mikhaildoc-documentat commented on metastore-import.tf
Они там есть, см. строчку 174

2025-01-10 05:23 UTC, Odyvia42 approved these changes

2025-01-10 14:00 UTC, lanieuszko approved these changes

2025-01-10 14:00 UTC, merged